### ISSUE TITLE
Local setup needs an update

### ISSUE THREAD

**Issue by gajop** [beyond-all-reason/teiserver#12]
https://github.com/beyond-all-reason/teiserver/blob/master/documents/dev_guides/local_setup.md

`git clone git@github.com:Teifion/teiserver.git`
wrong repo

```
mix deps.get
mix deps.compile
cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
cd ..
```

executing `mix deps.get` fails
```
mix deps.get

** (Code.LoadError) could not load /home/gajop/projects/teiserver/config/dev.secret.exs
    (elixir) lib/code.ex:1193: Code.find_file/2
    (elixir) lib/code.ex:758: Code.eval_file/2
    (mix) lib/mix/config.ex:158: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/config.ex:157: Mix.Config.__import__!/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:240: Code.eval_string/3
```

**Comment by Teifion** [comment]
Cheers, this will be fixed soon; I forgot to update it when I changed to the BAR repo.

**Comment by Teifion** [comment]
Fixed these issues, thank you for bringing them to my attention.

**Comment by gajop** [comment]
Fixed sure, but not yet merged to this repo =)
