### ISSUE TITLE
Failure to recieve probably an infolog blob * (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0xff

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#227]
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0xff
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
    (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_telemetry_in.ex:30: Teiserver.Protocols.Spring.TelemetryIn.do_handle/4
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_in.ex:82: Teiserver.Protocols.SpringIn.handle/2
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_in.ex:56: Teiserver.Protocols.SpringIn.data_in/2
    (teiserver 0.1.0) lib/teiserver/tcp/spring/spring_tcp_server.ex:265: Teiserver.SpringTcpServer.handle_info/2
Last message: {:tcp, #Port<0.42075>, "_BuMGlOZtE8selZMY0UPS5tcNb0GLCZdXrMM9ILKnqNAHIxdB_haaZWIMJ8h3aUiBn7qE-3U1hi6EmNgttFgRopuNsptFoFSXQ1ixOYSAS2mUSUzQ3V5NGgi4JxRAXOdgqGQniO3UXC0Ld86jwBu-aaFwq6e6HwKXOedqHA0fF5noxRaTCLFkk5Dx8JTLJebVFwY84nUXtRwNDqvwOaiXAxFi5qLsZCcmY3QPlBRKJkRA2gXOod30TewbyEkmgdSd8_mJfw3afuItXaDFsFwj3bs2FWZAlMe86EckIJ59EkihKm8RLEDWJiYI599GPx_-Al9sHb5CWQOW2yEniaF2icBLcNy4AUhGzWu90aVPOmBtU8ggkL7Wxmsz9F8b_LyDq1JsslLFOoIVRkyxeoRaUmL7RbraYuBtTrMxcxw_Na8NSCLBz8j5Zf89UsLVCpfPmYiGCnaqL0SZ3tYHVShmkYNiTkqIrIvkUL67cM9ZahCsbQKbIp6rA3iu_VZm7PtXdjcvfGNE8XUDGr4qGcjxYwFw1ggQ0z1Pv_UqJZekhhMqpVj9YWDf7EBKW2Ss3SESyxD-ksBfZIXAfrQ_9BkSXJY5r85wzwrtnMOpPZWKuMdDZFxvJunJfkg83vWkGow2q16gW7CGC8zp51irqYWTpOjFX6ZbVG4gY1FomxnUX1bNZVpfIQOMuR6jxRd7VqDWrVau-kRdjBpf4Cm5owma-AJ8EljZFamTkhGxQOc3fj8LXtw2q5WqWwccDVvJyfLYuJyprVhm-wqzJRMGk6dvVbsjvUyD5en2UepQtD1sRuZP1hIXw1KM1MaMLpFaymMWzQJCmxlHqTievhf8Jt6_laK0dzT6yyZ9uy1zWChEcJuu1r_awdvoblxlR_AXz5P9iPrT0=\n"}
2024-03-12 20:11:27.152 [error]  Ranch listener #Reference<0.375614269.3480748047.52965> had connection process started with Teiserver.SpringTcpServer:start_link/4 at #PID<0.22893.2> exit with reason: {%Postgrex.Error{message: nil, postgres: %{code: :character_not_in_repertoire, file: "mbutils.c", line: "1665", message: "invalid byte sequence for encoding \"UTF8\": 0xff", pg_code: "22021", routine: "report_invalid_encoding", severity: "ERROR", unknown: "ERROR", where: "unnamed portal parameter $1"}, connection_id: 225495, query: nil}, [{Ecto.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 913, error_info: %{module: Exception}]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 764]}, {Ecto.Repo.Schema, :"-do_insert/4-fun-3-", 15, [file: 'lib/ecto/repo/schema.ex', line: 377]}, {Teiserver.Protocols.Spring.TelemetryIn, :do_handle, 4, [file: 'lib/teiserver/protocols/spring/spring_telemetry_in.ex', line: 30]}, {Teiserver.Protocols.SpringIn, :handle, 2, [file: 'lib/teiserver/protocols/spring/spring_in.ex', line: 82]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2468]}, {Teiserver.Protocols.SpringIn, :data_in, 2, [file: 'lib/teiserver/protocols/spring/spring_in.ex', line: 56]}, {Teiserver.SpringTcpServer, :handle_info, 2, [file: 'lib/teiserver/tcp/spring/spring_tcp_server.ex', line: 265]}]}

**Comment by Beherith** [comment]
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire) invalid byte sequence for encoding "UTF8": 0xff
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
    (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_telemetry_in.ex:30: Teiserver.Protocols.Spring.TelemetryIn.do_handle/4
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_in.ex:82: Teiserver.Protocols.SpringIn.handle/2
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (teiserver 0.1.0) lib/teiserver/protocols/spring/spring_in.ex:56: Teiserver.Protocols.SpringIn.data_in/2
    (teiserver 0.1.0) lib/teiserver/tcp/spring/spring_tcp_server.ex:265: Teiserver.SpringTcpServer.handle_info/2
Last message: {:tcp, #Port<0.123036>, "qKStPRoTj37_cpFcfQQ2elvka1GrMWSjgmVu6f5uq8qijUiVbqpv0w6UgiJHm05i_3O0SDF10M90heInv8s71Oh2P8aI2L5zpvMB45J1AOlFXdU3eguXzXFYSxRnvgzzqOZsvWiRixcT4PUsX5Q3c20VOhE22EGnqMOqsUGsHrvJuzP0JiuMVWx8XDK6ymI5givk8ch6KyDJ9RwL16bVYYrz1dH49x5DSySKffOqsr7rgF3A5ki9axYox22aE6qNfNuXZpl6s09VNVe2pM-F43s6a4dioRKJYUWPeMTmEk-V0gl5whQBSmXHImPrjoFyuFFqYNEZZw32I0h8uNXDStRoW43SHIZyioT3CdOQHCezzcA-M6QjTLsDi9LyDUKYJCX9tDUWoeCarG89rbjyEeai3XoXpoJJsvXT3ji6SffDx9fYZWPcw2G7XbQ1oHCphUJa9f9C-u3v0_SG7rtpvlLXkN9cSBw7ZynGJGLJLM3JB89hzODndB19NJJaXMrtBhZM1oPFhIxvTX1ujoNqWbUfhd7-qoO9UCcFSV1VQrap2zahbVQkNNb3AV-LoPp6zZf4Ojl7MQ3py8uN6XjL89BwOmytuuuVGZu4FdjyFAufx3gZcrFb85LlecOz6x8Qbee6xHx-T8Nh1o9FrtlnnKzZ6x5YIngLXylGX98agmM5-fuwcEfQuAW3IGX8pWfGk1dFA7egQ9MZp9V-pBjoF_iL0ygEmm8ED--iJajFGmBEl-u--FnqexOSqzUaxcqmt_rCCEWWSD4qdfxXOeqDEh6HzrzB5S_gxiBXCAaKG7EEYVt6k_FzJsNBP3CRgUxc6drv9GDM6TmbqEgvccK8-hPdipTw7qqzQip9tVlcf08XknBUwDV9kMtUjleETdTIC4ibqLcJM_WyRF7BxbucTdqQ2u006kgn3-kkPz1-OOG2eDkcy8FoU0VG1eyh2Rz1qEfDUmD8pU_77DP-L95R2jbD7alNdmIj9hQmpRt1SkWypbi9MnQQVT0-TIkh2FcFukt0995skG_pAJ80eHaM6DVTZFHuxets1nAbtmjQw1nw1LybaWaeKJalVR71aYx3zeIk6fquOT1xjnXccxw1kq6aBiUtCZb7_-wwOuDLNrhcME2Qv0tX3XJ1YXznh_-FoXfAJbmfTzQ7AoyRIA6I87nz0z9-8hQsvHpjiGOGKA2yvqUOc1ZxNWNEm4ilH9tA3Evn_c7UibQ==\n"}
2024-03-12 21:20:43.084 [error]  Ranch listener #Reference<0.375614269.3480748047.52965> had connection process started with Teiserver.SpringTcpServer:start_link/4 at #PID<0.2732.7> exit with reason: {%Postgrex.Error{message: nil, postgres: %{code: :character_not_in_repertoire, file: "mbutils.c", line: "1665", message: "invalid byte sequence for encoding \"UTF8\": 0xff", pg_code: "22021", routine: "report_invalid_encoding", severity: "ERROR", unknown: "ERROR", where: "unnamed portal parameter $1"}, connection_id: 225499, query: nil}, [{Ecto.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 913, error_info: %{module: Exception}]}, {Ecto.Repo.Schema, :apply, 4, [file: 'lib/ecto/repo/schema.ex', line: 764]}, {Ecto.Repo.Schema, :"-do_insert/4-fun-3-", 15, [file: 'lib/ecto/repo/schema.ex', line: 377]}, {Teiserver.Protocols.Spring.TelemetryIn, :do_handle, 4, [file: 'lib/teiserver/protocols/spring/spring_telemetry_in.ex', line: 30]}, {Teiserver.Protocols.SpringIn, :handle, 2, [file: 'lib/teiserver/protocols/spring/spring_in.ex', line: 82]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2468]}, {Teiserver.Protocols.SpringIn, :data_in, 2, [file: 'lib/teiserver/protocols/spring/spring_in.ex', line: 56]}, {Teiserver.SpringTcpServer, :handle_info, 2, [file: 'lib/teiserver/tcp/spring/spring_tcp_server.ex', line: 265]}]}

**Comment by L-e-x-o-n** [comment]
This should be fixed by @Beherith
