### ISSUE TITLE
 GenServer #PID<0.4907.0> terminating ** (stop) exited in: GenServer.call(Nostrum.Api.Ratelimiter

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#230]
2024-03-12 21:50:06.656 [error] request_id=BridgeServer  GenServer #PID<0.4907.0> terminating
** (stop) exited in: GenServer.call(Nostrum.Api.Ratelimiter, {:queue, %{body: %{name: "Players in game: 182"}, headers: [{"content-type", "application/json"}], method: :patch, params: [], route: "/channels/931978699220320276"}}, 5000)
    ** (EXIT) time out
    (elixir 1.14.3) lib/gen_server.ex:1038: GenServer.call/3
    (nostrum 0.8.0) lib/nostrum/api/ratelimiter.ex:125: Nostrum.Api.Ratelimiter.queue/2
    (nostrum 0.8.0) lib/nostrum/api.ex:702: Nostrum.Api.modify_channel/3
    (teiserver 0.1.0) lib/teiserver/bridge/bridge_server.ex:448: Teiserver.Bridge.BridgeServer.change_channel_name/2
    (teiserver 0.1.0) lib/teiserver/bridge/bridge_server.ex:127: Teiserver.Bridge.BridgeServer.handle_info/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:update_stats, :player_count, 182}

**Comment by joshua-augustinus** [comment]
Just googling that https://hexdocs.pm/nostrum_heroku/Nostrum.Api.Ratelimiter.html
it mentions Discord API. Are you sure reenabling discord bridge hasn't caused new issues?

**Comment by L-e-x-o-n** [comment]
Looking into this as part of general Nostrum update and improvements.
