### ISSUE TITLE
[Bug]: (Enum.EmptyError) empty error during balance_battle request

### ISSUE THREAD

**Issue by L-e-x-o-n** [beyond-all-reason/teiserver#430]
### Describe the Bug

Logs:
```
Request: POST /teiserver/api/spads/balance_battle
** (exit) an exception was raised:
    ** (Enum.EmptyError) empty error
        (elixir 1.14.5) lib/enum.ex:1855: anonymous fn/0 in Enum.max/1
        (teiserver 0.1.0) lib/teiserver_web/controllers/api/spads_controller.ex:164: TeiserverWeb.API.SpadsController.balance_battle/2
        (teiserver 0.1.0) lib/teiserver_web/controllers/api/spads_controller.ex:1: TeiserverWeb.API.SpadsController.action/2
        (teiserver 0.1.0) lib/teiserver_web/controllers/api/spads_controller.ex:1: TeiserverWeb.API.SpadsController.phoenix_controller_pipeline/2
        (phoenix 1.7.6) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (teiserver 0.1.0) lib/teiserver_web/endpoint.ex:1: TeiserverWeb.Endpoint.plug_builder_call/2
        (teiserver 0.1.0) lib/teiserver_web/endpoint.ex:1: TeiserverWeb.Endpoint.call/2
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
```

```ex
          team_size =
            balance_result.team_sizes
            |> Map.values()
            |> Enum.max()
            ```
It seems `team_sizes` might be empty.

### Reproduce the bug

Unfortunately the logs don't contain any other details. Don't know the team count, team size or balance algorithm used. There are only 2 such errors recently in logs so I think it's probably some edge case.

**Comment by jauggy** [comment]
@L-e-x-o-n you can assign to me.

**Comment by jauggy** [comment]
So I had an idea to press balance as spec when there are no players - but it won't even let you do that.

**Comment by jauggy** [comment]
@L-e-x-o-n where are the logs stored? Want to try deliberately raising errors on my local environment.

**Comment by L-e-x-o-n** [comment]
When running it locally over WSL? Not sure if they are saved, but wouldn't you be able to see them when starting the server with `mix phx.server`?

**Comment by jauggy** [comment]
![Screenshot 2024-09-20 at 8 56 59 AM](https://github.com/user-attachments/assets/6ed27a40-3c59-4a25-8774-48cd9b646c80)

Interesting that Enum.max generates that error when array is empty but not when array is nil

**Comment by jauggy** [comment]
![Screenshot 2024-09-20 at 8 59 26 AM](https://github.com/user-attachments/assets/3cdf6a6b-3cf1-49cb-867d-79f34f93ce28)
Also get that error with empty map which is the default for team_sizes
